### ISSUE TITLE
Move all apps to Python 3

### ISSUE THREAD

**Issue by iambibhas** [hasgeek/hgapp#39]
Py2 is reaching EOL. All apps need to port to Py3. We're using `2to3` to update codes and creating PR. Going to tag this issue in all the PRs to keep track of them.

**Comment by iambibhas** [comment]
Issue with moving Hasjob, it's throwing this exception - 

```
~/W/h/hasjob ❯❯❯ FLASK_ENV=development ./runserver.py                   (hasgeekpinned3)  ✘ 1 py3 ✭ ✱
Traceback (most recent call last):
  File "./runserver.py", line 5, in <module>
    from hasjob import app
  File "/Users/bibhas/Work/hasgeek/hasjob/hasjob/__init__.py", line 32, in <module>
    from . import models, views  # NOQA
  File "/Users/bibhas/Work/hasgeek/hasjob/hasjob/models/__init__.py", line 18, in <module>
    class POST_STATE(LabeledEnum):
  File "/Users/bibhas/Work/hasgeek/hasjob/hasjob/models/__init__.py", line 34, in POST_STATE
    UNPUBLISHED = {DRAFT, PENDING}
TypeError: unhashable type: '_LazyString'
```

**Comment by jace** [comment]
> It probably has something to do with flask-babelex. More issue there - [hasgeek/baseframe#181 (comment)](https://github.com/hasgeek/baseframe/issues/181#issuecomment-562181415)
> 
> No error if we use gettext instead of lazy gettext.

This has been resolved via https://github.com/hasgeek/flask-babelhg
